### ISSUE TITLE
Version of Node?

### ISSUE THREAD

**Issue by joshholmes** [ritazh/devopsfun#13]
On http://ritazh.github.io/devopsfun/installing-node/, you mention say to download and install node but there's no mention of which version of node this has been tested with. There are breaking changes with the latest versions so if they have an older version as in they are doing anything with our Johnny-Five that doesn't work with the latest yet, what's the story there?

**Comment by ritazh** [comment]
@joshholmes Good catch! The sample Node.js app has been tested with node 5.5.0 and npm 3.3.12. I will add it to this module.

**Comment by ritazh** [comment]
Closed via 30f395f
