### ISSUE TITLE
SSH-ADD / Windows / Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by julienstroheker** [ritazh/devopsfun#17]
In the module : Deploying app : https://ritazh.github.io/devopsfun/deploying-app/

When I try : 
`ssh-add.exe MYKEY`
I have : 
`Could not open a connection to your authentication agent.`

I am using Windows 10

**Comment by julienstroheker** [comment]
If you have this issue : 

In the CMD window, type the following command:
`cd path-to-Git/bin` (for me : cd C:\Program Files\Git\bin)
`bash`
`exec ssh-agent bash`
`ssh-add MYKEY`

**Comment by ritazh** [comment]
@julienstroheker :+1: :fireworks: Will add this to the module.
