### ISSUE TITLE
node -v should be nodejs -v

### ISSUE THREAD

**Issue by robwalkerco** [ritazh/devopsfun#30]
On https://ritazh.github.io/devopsfun/continuous-deploy-app/#setting-up-node
The command for testing the node install should be `nodejs -v`. It errors out with `node -v`

**Comment by robwalkerco** [comment]
Or perhaps I've git something else wrong that means that `node` is not available! (I installed `nodejs` on the box manually.

**Comment by ritazh** [comment]
@robwalkerco Thanks for reporting this. 

Looks like you installed nodejs on the server with `apt-get`. 
You can link `node` to `nodejs` so that both `nodejs -v` and `node -v` will work:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`
