### ISSUE TITLE
NodeJS configuration has been moved 

### ISSUE THREAD

**Issue by DrJukka** [ritazh/devopsfun#31]
Please update the http://ritazh.github.io/devopsfun/continuous-deploy-app/#setting-up-node 

NodeJS configurations has been moved to configureTools from the configure

**Comment by ritazh** [comment]
@DrJukka Do you have a screen shot of the UI? Thanks!

**Comment by DrJukka** [comment]
![2016-05-18](https://cloud.githubusercontent.com/assets/5235141/15347922/a418794c-1cce-11e6-92af-3c1aed83e26e.png)
![2016-05-18 2](https://cloud.githubusercontent.com/assets/5235141/15347937/c392f996-1cce-11e6-8641-358110d99e2a.png)

Do have, but I'm having mixed language there, partly Finish, partly English

**Comment by ritazh** [comment]
@DrJukka Thank you!

**Comment by ritazh** [comment]
Closed via b453db0
